version: '3'

services:
  web:
    build: ./Web
    environment:
      - DJANGO_SUPERUSER_PASSWORD=1234
    command:
      python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3303:3306'
    environment:
      MYSQL_DATABASE: 'mesDB'
      MYSQL_USER: 'denis'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
