# Generated by Django 4.0.4 on 2022-05-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_alter_message_options_remove_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
