# Generated by Django 4.0.4 on 2022-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
