# Generated by Django 4.0.4 on 2022-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.UUIDField>'),
        ),
    ]
