# Generated by Django 4.0.4 on 2022-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='<bound method UUIDField.get_db_prep_value of <django.db.models.fields.UUIDField>>'),
        ),
    ]
