# Generated by Django 4.0.4 on 2022-05-24 18:49

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=chat.models.Room.__str__),
        ),
    ]
