# Generated by Django 4.0.4 on 2022-05-24 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ),
    ]
