# Generated by Django 4.0.4 on 2022-05-24 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
