# Generated by Django 4.0.4 on 2022-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='auth.User, <django.db.models.query_utils.DeferredAttribute object at 0x7fea6bc238e0>', max_length=255),
        ),
    ]
