# Generated by Django 4.0.4 on 2022-05-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0005_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
