# Generated by Django 4.0.4 on 2022-05-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
